In [1]:
# ==============================
# Tanzila Islam
# Email: tanzilamohita@gmail.com
# ===============================

In [7]:
import numpy as np
import pandas as pd
from Data_Processing import one_hot_encode_snp_array
from DeepCGP_ import compress_data

import warnings
warnings.filterwarnings("ignore")

In [8]:
# read data
data = pd.read_csv(f'../Data/X.csv', index_col=0)
print(data.iloc[:5, :5])

              V1 V2 V3 V4 V5
PURPLE         A  G  A  A  A
KinShanZim     A  G  A  A  G
N32            A  G  C  A  G
Dular          A  G  C  A  G
HashikalmiAus  A  G  C  A  G


In [9]:
# convert to one hot encoding
snp_array = data.astype(str).values
one_hot = one_hot_encode_snp_array(snp_array)
print(one_hot)
print(one_hot.shape)

[[1 0 0 ... 0 1 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
(189, 56)


In [14]:
best_config = {
    "InputDim": 28,
    "Compress": [14, 7, 3],
    "BatchSize": 52,
    "LearningRate": 0.001,
    "Epochs": 200,
}

X = one_hot.astype(np.float32)
compressed = compress_data(X, best_config, seed=42, verbose=True)

→ Chunk 1/2 | chunk shape=(189, 28)
→ Chunk 2/2 | chunk shape=(189, 28)
Final compressed shape: (189, 6)
